# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Album < Formula
  desc "Create a SmugMug album from a Strava activity"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.22"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.22/go-scripts_0.0.22_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "13db8fbd4e2dec4d6aa4c0a861933aa734c7f06ab0e56594bd1d6bd8f99561c7"

      def install
        bin.install "album"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.22/go-scripts_0.0.22_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cfabc8dc804278daaf8d7f05f48bea25b84521db9631d1f7d436d31db9401bea"

      def install
        bin.install "album"
      end
    end
  end
end
