# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Dustbin < Formula
  desc "Clean up file names"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.7"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.7/go-scripts_0.0.7_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d81a748b4c278943cc2144219601c823a254cdc019a7a0cf18e333e86619f880"

      def install
        bin.install "dustbin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.7/go-scripts_0.0.7_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "32923ccdec19985df16caad9f72e55d75fd2f3f8ddf7610a7a79cddef37d838c"

      def install
        bin.install "dustbin"
      end
    end
  end
end
