# typed: false
# frozen_string_literal: true

require_relative "lib/private_strategy"

# This file was generated by GoReleaser. DO NOT EDIT.
class Dustbin < Formula
  desc "Clean up file names"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.4"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.4/go-scripts_0.0.4_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "86a50df33a773aa9322b5efd539780896be43a1b2927fb1684f9f5b18b3512c3"

      def install
        bin.install "dustbin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.4/go-scripts_0.0.4_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3b2f22e19c37fdeea1f901a267523d86db7aed1eb60ada0df3501f07d7d3f2e3"

      def install
        bin.install "dustbin"
      end
    end
  end
end
