# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Fm < Formula
  desc "Manipulate Excel on the command line"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.10"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.10/go-scripts_0.0.10_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "149dfdcf1847a3d28dc89dbe209fcb90f03e7e3e3802fe71e119e68e68b9cf59"

      def install
        bin.install "fm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.10/go-scripts_0.0.10_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4877713df225cfee4b4466855890dd13abbfc3046834366ff810cfe39216b12c"

      def install
        bin.install "fm"
      end
    end
  end
end
