# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Fm < Formula
  desc "Manipulate Excel on the command line"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.14"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.14/go-scripts_0.0.14_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6cf86cf6c447d9ffe50f435552536a9b50ea7efd0f4617b258316efa196156d3"

      def install
        bin.install "fm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.14/go-scripts_0.0.14_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2630b09970438e44562c734af20ec0a06017e5399e308671720252eff7d8e487"

      def install
        bin.install "fm"
      end
    end
  end
end
