# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genwith < Formula
  desc "Code generation tool for client with functional options"
  homepage "https://github.com/bzimmer/genwith"
  version "0.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/genwith/releases/download/v0.7.3/genwith_0.7.3_darwin_amd64.tar.gz"
      sha256 "7609a623c6928aa870d407fae44494d347f3e19b9707aec38f4c5e4facbf2ff1"

      def install
        bin.install "genwith"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/genwith/releases/download/v0.7.3/genwith_0.7.3_darwin_arm64.tar.gz"
      sha256 "f342f1adeeb2f8065b28e424abe9587ba223bb4fda25f1f8b4cfa1691f0b0942"

      def install
        bin.install "genwith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bzimmer/genwith/releases/download/v0.7.3/genwith_0.7.3_linux_arm64.tar.gz"
      sha256 "19e06a719c6e8e64ee6ca5197ccdfc9475101f10ce90a0862a1d1eb7d3453d8b"

      def install
        bin.install "genwith"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/genwith/releases/download/v0.7.3/genwith_0.7.3_linux_amd64.tar.gz"
      sha256 "f52364f973c7fe2dcc768ff51c9041541acea64823ef5f18d1e40eeb9fc31782"

      def install
        bin.install "genwith"
      end
    end
  end
end
