# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gravl < Formula
  desc "Command line clients for activity-related services"
  homepage "https://github.com/bzimmer/gravl"
  version "0.7.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/gravl/releases/download/v0.7.4/gravl_0.7.4_Darwin_x86_64.tar.gz"
      sha256 "91f4ced427ced38244c743420b6c25cbd5759aa2482fbc0d806542317292cc42"

      def install
        bin.install "gravl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/gravl/releases/download/v0.7.4/gravl_0.7.4_Darwin_arm64.tar.gz"
      sha256 "98cf4a1979904da7dcc4d78b7b6dc0e5e6c9a27c736fd96c3738d4fa35118ec5"

      def install
        bin.install "gravl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/gravl/releases/download/v0.7.4/gravl_0.7.4_Linux_x86_64.tar.gz"
      sha256 "511019e564b46a86461a8ed49f3ac49cb34c0669e379b4153e47ccce532d6dda"

      def install
        bin.install "gravl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bzimmer/gravl/releases/download/v0.7.4/gravl_0.7.4_Linux_arm64.tar.gz"
      sha256 "dddd4815f76b7f289a1cf2e83a254b3b3eff632f984f46453ff6499f8b6dd30d"

      def install
        bin.install "gravl"
      end
    end
  end
end
