# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gravl < Formula
  desc "Command line clients for activity-related services"
  homepage "https://github.com/bzimmer/gravl"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/gravl/releases/download/v0.9.2/gravl_0.9.2_Darwin_x86_64.tar.gz"
      sha256 "ffebf59b318ed4fd4e2fcaa026805957393089ac4a09aa98dc25d72b749a7ccb"

      def install
        bin.install "gravl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/gravl/releases/download/v0.9.2/gravl_0.9.2_Darwin_arm64.tar.gz"
      sha256 "61cbb6274e849e90579949a99848f41ee4aceca5f10246274f35d3c8cc44d2d0"

      def install
        bin.install "gravl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bzimmer/gravl/releases/download/v0.9.2/gravl_0.9.2_Linux_arm64.tar.gz"
      sha256 "0bc96971ae6c9eec3cb421c9ee0e2fa7f733ba5eda0d2ab523490de23745aa9e"

      def install
        bin.install "gravl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/gravl/releases/download/v0.9.2/gravl_0.9.2_Linux_x86_64.tar.gz"
      sha256 "bbacdd94875be8e8398251ae403ec176a94079c6af6763c4844c377c92a071ec"

      def install
        bin.install "gravl"
      end
    end
  end
end
