# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Houdah < Formula
  desc "Create gpx files from Strava activities for HoudahGeo"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.16"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.16/go-scripts_0.0.16_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8c582cd3dc7994cf32013e19ce6b85ef00fe2b7b7da820dca3fdf0d6e10c2e83"

      def install
        bin.install "houdah"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.16/go-scripts_0.0.16_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "74d82570845697cfe80783d6815377d1968e9d46deb655fe9a0356fdc1e036c0"

      def install
        bin.install "houdah"
      end
    end
  end
end
