# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Houdah < Formula
  desc "Create gpx files from Strava activities for HoudahGeo"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.20"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.20/go-scripts_0.0.20_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "58faa8db5522e9c4c4a089b875b5730a19d226b1ac72e1f1e24d83372ccb5fed"

      def install
        bin.install "houdah"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.20/go-scripts_0.0.20_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f287e1483aa804f2de938573e463543ae4976b95350a2d437c32e4786e461cef"

      def install
        bin.install "houdah"
      end
    end
  end
end
