# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ma < Formula
  desc "Simple tools for managing media files with SmugMug"
  homepage "https://github.com/bzimmer/ma"
  version "0.9.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/bzimmer/ma/releases/download/v0.9.0/ma_0.9.0_darwin_amd64.tar.gz"
      sha256 "aeef917aaeec68d40ee6e415d55f843148c5ffb805cbdb16d31cf6829b2ffec9"

      def install
        bin.install "ma"
      end
    end
    on_arm do
      url "https://github.com/bzimmer/ma/releases/download/v0.9.0/ma_0.9.0_darwin_arm64.tar.gz"
      sha256 "e2be51c8723afa2a5064e86de8af9bbcbcbd74e56ef9f664d57a58c2c38a9604"

      def install
        bin.install "ma"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bzimmer/ma/releases/download/v0.9.0/ma_0.9.0_linux_amd64.tar.gz"
        sha256 "d3880d91e7aa86839f25c4486e0cb739f816257663fe8ce20c2ac49dd3b39108"

        def install
          bin.install "ma"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bzimmer/ma/releases/download/v0.9.0/ma_0.9.0_linux_arm64.tar.gz"
        sha256 "b63593595ab9b955f31f4534f3521a04211e4fb08d9fa7eea230721d94c784b5"

        def install
          bin.install "ma"
        end
      end
    end
  end
end
