# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ma < Formula
  desc "Simple tools for managing media files with SmugMug"
  homepage "https://github.com/bzimmer/ma"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/ma/releases/download/v0.6.1/ma_0.6.1_Darwin_arm64.tar.gz"
      sha256 "11bfa8aa740f4c0b1d98abe3b71a8cfcc7ec9740285c40a385bc3aebc8db2b44"

      def install
        bin.install "ma"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/ma/releases/download/v0.6.1/ma_0.6.1_Darwin_x86_64.tar.gz"
      sha256 "7631374588feb5654269b8112f2e27020448bb33854a3800c6c16fe42f74e9ef"

      def install
        bin.install "ma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/ma/releases/download/v0.6.1/ma_0.6.1_Linux_x86_64.tar.gz"
      sha256 "ff2fdcfcfa04d92e1542fbc16920a3ac7ac582cb78352dc9bf23949f74fd8f9c"

      def install
        bin.install "ma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bzimmer/ma/releases/download/v0.6.1/ma_0.6.1_Linux_arm64.tar.gz"
      sha256 "09f5d347f779e71b982312997f19e7535c96296a01d2651989c3715dc0971c62"

      def install
        bin.install "ma"
      end
    end
  end
end
