# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qordle < Formula
  desc "Wordle problem solver"
  homepage "https://github.com/bzimmer/qordle"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/qordle/releases/download/v0.2.0/qordle_0.2.0_Darwin_arm64.tar.gz"
      sha256 "a3dc1aa2a7ad990300eff4d10049162d53bf6daaecba99a8912016b7edda966a"

      def install
        bin.install "qordle"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/qordle/releases/download/v0.2.0/qordle_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "0b812465a870e52db804c27ef01bb60b1aa3fea037a4f2b49c85e60429297b83"

      def install
        bin.install "qordle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bzimmer/qordle/releases/download/v0.2.0/qordle_0.2.0_Linux_arm64.tar.gz"
      sha256 "2b30fbf3f74b1fc425ce77a0f84b641a3dd77171783135526a0b21e22b9c5a79"

      def install
        bin.install "qordle"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/qordle/releases/download/v0.2.0/qordle_0.2.0_Linux_x86_64.tar.gz"
      sha256 "9acfaf6b01876b07780373b4c693caa157bde2b4e9dd02a9434acca74fa3b9c3"

      def install
        bin.install "qordle"
      end
    end
  end
end
