# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qordle < Formula
  desc "Wordle problem solver"
  homepage "https://github.com/bzimmer/qordle"
  version "0.3.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.13/qordle_0.3.13_darwin_amd64.tar.gz"
      sha256 "c59a2636488f2d61ce3534ec9f2dce288961ced59527690f2aeb2b464e977c72"

      def install
        bin.install "qordle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.13/qordle_0.3.13_darwin_arm64.tar.gz"
      sha256 "992aed720684b9d69d622e248ca0cc2deaa4224fd76bd8cfd155ab1cd93c030a"

      def install
        bin.install "qordle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.13/qordle_0.3.13_linux_arm64.tar.gz"
      sha256 "46a40ffa8f557a6e35849db0ba8678ce9e9dfa7ec081ebed5580070e74fd3ced"

      def install
        bin.install "qordle"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.13/qordle_0.3.13_linux_amd64.tar.gz"
      sha256 "7e226a5debb1661ad6e1f5690e89939942378d8bdbc770b744978e5cb0ec32e4"

      def install
        bin.install "qordle"
      end
    end
  end
end
