# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qordle < Formula
  desc "Wordle problem solver"
  homepage "https://github.com/bzimmer/qordle"
  version "0.3.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.14/qordle_0.3.14_darwin_arm64.tar.gz"
      sha256 "c5f08e4c7c09fa79e8633738152be720531729a0fc8d8b0ab0f546bcc2974eb0"

      def install
        bin.install "qordle"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.14/qordle_0.3.14_darwin_amd64.tar.gz"
      sha256 "f2bd710a448a21d02caa99b389ff93ddfc0eeaf102112ed834e413d2e52d9687"

      def install
        bin.install "qordle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.14/qordle_0.3.14_linux_arm64.tar.gz"
      sha256 "cc5acbeacba9b6f65a485688df8a99b9d74c83a303218b9527ad761e8bf426c5"

      def install
        bin.install "qordle"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.14/qordle_0.3.14_linux_amd64.tar.gz"
      sha256 "28a2bda3a80ba60d204af8c5e657d8387f7f7347e2b247f87cd2b67d54b1a4fc"

      def install
        bin.install "qordle"
      end
    end
  end
end
