# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qordled < Formula
  desc "Wordle problem solver daemon"
  homepage "https://github.com/bzimmer/qordle"
  version "0.3.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.17/qordle_0.3.17_darwin_amd64.tar.gz"
      sha256 "1a5a6ccd1f10fee0ad5eccccfd1846de3c68d4bdc603aeda8388adfdc345ed22"

      def install
        bin.install "qordled"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.17/qordle_0.3.17_darwin_arm64.tar.gz"
      sha256 "868b24c8c692a067fbc6f5c09e7cca362059e75e4821736f6d08ae7e9df247af"

      def install
        bin.install "qordled"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.17/qordle_0.3.17_linux_arm64.tar.gz"
      sha256 "c51f7414badf7358c6ed78cffe9b396f6515ca10c32ccc652016003a9c41d098"

      def install
        bin.install "qordled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/qordle/releases/download/v0.3.17/qordle_0.3.17_linux_amd64.tar.gz"
      sha256 "79f459be883997a1be58c3eadaf8eb7d1f64a84b8468deb56fca4f5fb1b83c58"

      def install
        bin.install "qordled"
      end
    end
  end
end
