# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Semver < Formula
  desc "Determine the next semantic version"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.30"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.30/go-scripts_0.0.30_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "795c111a170092e951dd98213838159ca8df69ec53bdc826819d9a70766666ad"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.30/go-scripts_0.0.30_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "42012f584c140904af0e48d345ed7be2d392238a2f7ace6ce73acd57f0c66cbd"

      def install
        bin.install "semver"
      end
    end
  end
end
