# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Semver < Formula
  desc "Determine the next semantic version"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.27"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.27/go-scripts_0.0.27_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c08a171504293eb4a71fc432411d9d91ac7f64d1e336e08d566875b3345960f9"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.27/go-scripts_0.0.27_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a97cd4e14952c22ddeedf6c583c85c5f934da42be40047f1f648b2350b4ab2ac"

      def install
        bin.install "semver"
      end
    end
  end
end
