# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Serve < Formula
  desc "Serve static files over http(s)"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.9"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.9/go-scripts_0.0.9_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f386825c77141539bdb9ac7408722fbd783e2bf3996b04c8c30be299ca10c178"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.9/go-scripts_0.0.9_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c5128a4a6ee4e48ca27e1a22735d09c515a82579a30a227e62ee948e17948b0e"

      def install
        bin.install "serve"
      end
    end
  end
end
