# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Tg < Formula
  desc "Upload files to Telegram"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.18"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.18/go-scripts_0.0.18_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b36035735b34255f513f9eafca788101e9b06b1ef770be1b68c67e214f6e0cb9"

      def install
        bin.install "tg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.18/go-scripts_0.0.18_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "97491e45bf43097c47eed0a86526dbf2a8e2a797ea7468210a68f4483d7dffd4"

      def install
        bin.install "tg"
      end
    end
  end
end
