# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Tg < Formula
  desc "Upload files to Telegram"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.17"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.17/go-scripts_0.0.17_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fced4c0230b2db08da454eef13cfe5a6e72cc145c91e4908499704019946599e"

      def install
        bin.install "tg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.17/go-scripts_0.0.17_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "15b24306eb3f8da7faa230bb5724c37924abd90f98d49f7ef040ed31a2fc819c"

      def install
        bin.install "tg"
      end
    end
  end
end
