# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Tripit < Formula
  desc "Export TripIt data to json"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.38"
  license "MIT"
  depends_on :macos

  on_arm do
    url "https://github.com/bzimmer/go-scripts/releases/download/v0.0.38/go-scripts_0.0.38_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "807b1beea88c3313cf7d67f5fc612c43ac1da4c3f090983fe7a063491afac48a"

    def install
      bin.install "tripit"
    end
  end
end
