# This file was generated by GoReleaser. DO NOT EDIT.
cask "gravl" do
  name "gravl"
  desc "Command line clients for activity-related services"
  homepage "https://github.com/bzimmer/gravl"
  version "0.11.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gravl"

  on_macos do
    on_intel do
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_darwin_amd64.tar.gz"
      sha256 "7b18ac9737cba5f0916d27b5cc6100f391dc2b9e44f7b58570e0845458adf61f"
    end
    on_arm do
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_darwin_arm64.tar.gz"
      sha256 "f53251e2de4c89a3beba1c662a7cd495ab1de7380855ca24ff4f61fcbc9a45bd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_linux_amd64.tar.gz"
      sha256 "80d10b7b9000462e96e7587237b051d22c16ffd35521b699772049ea39d06a97"
    end
    on_arm do
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_linux_arm64.tar.gz"
      sha256 "ad3469e1573fd49005c181a5f569db060593451e4a284b50b387e9b31444281c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gravl"]
    end
  end

  # No zap stanza required
end
