# This file was generated by GoReleaser. DO NOT EDIT.
cask "gravl" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "25f8f98404977803ed6caee26451c7e75dff9eaf6976a83c85a8946cc9afcf11"
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d41dd676644d10d36b7a55d3c5f51c11782a26946a41d443c36df865f9bbd1c5"
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "869db826ec33be6bc120be8b558bc6654001684f3008b26510a5235d7b96796d"
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe326316b79eb8bf033e4660e0fa45801d936c4e6348badd61b8f51d6032ed90"
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gravl"
  desc "Command line clients for activity-related services"
  homepage "https://github.com/bzimmer/gravl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gravl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gravl"]
    end
  end

  # No zap stanza required
end
