# This file was generated by GoReleaser. DO NOT EDIT.
cask "gravl" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "a5da8fcbd87a677f2955c205025bbdb74e34ba9fadfe9fb0d48a100f4c42fc82"
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc6a0d1c8fa177e83bd10ae0f9c18213370400446e624c2ee098d7733e9e000c"
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bdede76e0d446e521848199c9dacb9526de7b1dda53585f6e700a7db0339ea05"
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1acffecc504bc2d0daeb496fa1912641cc2229f37dfcae188a4b7b29641e0d51"
      url "https://github.com/bzimmer/gravl/releases/download/v#{version}/gravl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gravl"
  desc "Command line clients for activity-related services"
  homepage "https://github.com/bzimmer/gravl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gravl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gravl"]
    end
  end

  # No zap stanza required

end
