# This file was generated by GoReleaser. DO NOT EDIT.
cask "ma" do
  name "ma"
  desc "Simple tools for managing media files with SmugMug"
  homepage "https://github.com/bzimmer/ma"
  version "0.10.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ma"

  on_macos do
    on_intel do
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_darwin_amd64.tar.gz"
      sha256 "8a3454c3d5527d84d587b982235e234b8e5b677a9d9e576f38bf4d581ebd098a"
    end
    on_arm do
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_darwin_arm64.tar.gz"
      sha256 "914f5df753302d47eeaebc815b6e58b21f7823ae9e5c338a8e0f5251eb82280c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_linux_amd64.tar.gz"
      sha256 "7fb345ece41436a61cd783a8fffa6e6388bc88371c1e1dccb718e80d6240646b"
    end
    on_arm do
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_linux_arm64.tar.gz"
      sha256 "b7603549118f3659c43b7f9fb8399e56f993f226470dd17915f6bdff854b0156"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ma"]
    end
  end

  # No zap stanza required
end
