# This file was generated by GoReleaser. DO NOT EDIT.
cask "ma" do
  name "ma"
  desc "Simple tools for managing media files with SmugMug"
  homepage "https://github.com/bzimmer/ma"
  version "0.10.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ma"

  on_macos do
    on_intel do
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_darwin_amd64.tar.gz"
      sha256 "1684443544a5678f13b445ec6e015f67b37499ab64c2b7805fbddeb4d78a6ee3"
    end
    on_arm do
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_darwin_arm64.tar.gz"
      sha256 "7c372a44d8df48998c621c39b2a9fecf7003b3722551979dda6cbb4d71d4f51f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_linux_amd64.tar.gz"
      sha256 "90a99363fc607d2a9a1b3dcc3659d89bce349787c93cf54286b4c0a5f71ce413"
    end
    on_arm do
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_linux_arm64.tar.gz"
      sha256 "66de2338efa8f2369083f3781e1616a0c926c3687cf35717428b41075537046f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ma"]
    end
  end

  # No zap stanza required
end
