# This file was generated by GoReleaser. DO NOT EDIT.
cask "ma" do
  version "0.11.1"

  on_macos do
    on_intel do
      sha256 "2f390637bd546ee3d319bd41edb604db1da1b9ffa33a8a98911677fc639fad22"
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db83475849a129c16362bfd390aa5c6d7f1ff876924e79dd090fbe442935180a"
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "65282998e56e88ec27554ad97eb05f798da1d58d8eb12dde560660a29e30e02b"
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4cd6e2959b5c8765bcaeb320fc387a5a1631ad6f3e71f5fe0fc6959c62771eda"
      url "https://github.com/bzimmer/ma/releases/download/v#{version}/ma_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ma"
  desc "Simple tools for managing media files with SmugMug"
  homepage "https://github.com/bzimmer/ma"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ma"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ma"]
    end
  end

  # No zap stanza required

end
