# This file was generated by GoReleaser. DO NOT EDIT.
cask "qordled" do
  name "qordled"
  desc "Wordle problem solver daemon"
  homepage "https://github.com/bzimmer/qordle"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qordled"

  on_macos do
    on_intel do
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_darwin_amd64.tar.gz"
      sha256 "3509a52de62f2ab0f83eba2a107f5c0e816dfa2e3d0d61bad759b4d673f9404d"
    end
    on_arm do
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_darwin_arm64.tar.gz"
      sha256 "cd09a8ffab1eac8b7c5f77f85b498cdbd77c6dedc137f6fe0c588bd2eb81fc03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_linux_amd64.tar.gz"
      sha256 "d0b6ea295172ba413959a2df30a560e73e33bf02c73f3344f32ea02b385a2116"
    end
    on_arm do
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_linux_arm64.tar.gz"
      sha256 "8bb5eb825aa5556b67b334bd48cb905ab19517af3ad925f86a36eb53e874a901"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ma"]
    end
  end

  # No zap stanza required
end
