# This file was generated by GoReleaser. DO NOT EDIT.
cask "qordle" do
  version "0.4.4"

  on_macos do
    on_intel do
      sha256 "dc7b2011e0c759749adf1c1d176591c7a5046fd489165160904021ac12352359"
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9ba0f6b02e0bad41f4c3c4b1c7d743b6853cf1f3a4c86ea9255cf6dd1afbec8"
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "704d96601bae422536d538c8f060528db9f1e2a6a692f35d9c8bd211c403d7bf"
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a7cd6b413596b43acccd449d0afe945747df6021d72b0dc54a64afa48b5210db"
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qordle"
  desc "Wordle problem solver"
  homepage "https://github.com/bzimmer/qordle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qordle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qordle"]
    end
  end

  # No zap stanza required

end
