# This file was generated by GoReleaser. DO NOT EDIT.
cask "qordle" do
  name "qordle"
  desc "Wordle problem solver"
  homepage "https://github.com/bzimmer/qordle"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qordle"

  on_macos do
    on_intel do
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_darwin_amd64.tar.gz"
      sha256 "5e8753d4572488543cb7a0d2aa4eb4cf212ee255f5bbca9649bf49127c49b636"
    end
    on_arm do
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_darwin_arm64.tar.gz"
      sha256 "943732a1318c9004a9556a0f66b8159e84fa990759632f3560ac621c4b81fba6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_linux_amd64.tar.gz"
      sha256 "ee3ae83e3e8988261f849e6e13176d2234f2c67f72c468aaa46368fad9f542a1"
    end
    on_arm do
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_linux_arm64.tar.gz"
      sha256 "2f23b3267ac38115b627de9802c678c7daf0868556abce161e613ad70a0e4f12"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qordle"]
    end
  end

  # No zap stanza required
end
