# This file was generated by GoReleaser. DO NOT EDIT.
cask "qordle" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "cef1fa5da50c8f09303913c5e9e9b838404172ba62c9aed2656d93819af8284b"
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d6ad0296628454cf4848d30a473fffd751e2f0707e3c3a633a34597d50ebf87e"
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "37684975dc03f5aa4f7e6540950da9fcd4ffee8e4b3cc9a25321f0d21aeb11b6"
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd67f191c435068a66e79158f7d0ee8443e6238710c4104231f19b99a6ecfe23"
      url "https://github.com/bzimmer/qordle/releases/download/v#{version}/qordle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qordle"
  desc "Wordle problem solver"
  homepage "https://github.com/bzimmer/qordle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qordle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qordle"]
    end
  end

  # No zap stanza required
end
