# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  name "semver"
  desc "Determine the next semantic version"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.42"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver"

  on_macos do
    on_arm do
      url "https://github.com/bzimmer/go-scripts/releases/download/v#{version}/go-scripts_#{version}_darwin_arm64.tar.gz"
      sha256 "d9e1e53572be5471b7c134d415a6776e9bbe5d3c16466eed0d30795c24ce1284"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ma"]
    end
  end

  # No zap stanza required
end
