# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  name "semver"
  desc "Determine the next semantic version"
  homepage "https://github.com/bzimmer/go-scripts"
  version "0.0.43"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver"

  on_macos do
    on_arm do
      url "https://github.com/bzimmer/go-scripts/releases/download/v#{version}/go-scripts_#{version}_darwin_arm64.tar.gz"
      sha256 "b2c128435527858bc3037d9328810bd762d089af37d75ebe8e9abfebb375cc60"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ma"]
    end
  end

  # No zap stanza required
end
